// Generated by WASMVoodooCompile (voodoomc) from 'C:\Users\grego\Bruja\third_party\chromium-src\extensions\common\mojom\frame.mojom'. Do not edit by hand -- edit the .voodoom source and regenerate.
#ifndef FRAME_EXTENSIONS_H_
#define FRAME_EXTENSIONS_H_

#include "mojo/public/cpp/bindings/lib/interface_control_messages.h"
#include "mojo/public/cpp/bindings/lib/multiplex_router.h"
#include "mojo/public/cpp/bindings/lib/response_dispatcher.h"
#include "mojo/public/cpp/bindings/lib/wire_primitives.h"
#include "mojo/public/cpp/bindings/message.h"
#include "src/sandbox/cage-allocator.h"
#include "mojo/public/cpp/bindings/pending_associated_receiver.h"
#include "mojo/public/cpp/bindings/pending_associated_remote.h"
#include "mojo/public/cpp/bindings/pending_receiver.h"
#include "mojo/public/cpp/bindings/pending_remote.h"
#include "base/callback.h"
#include "base/expected.h"
#include "mojo/public/cpp/bindings/lib/type_intern.h"
#include "mojo/public/cpp/system/handle.h"
#include "mojo/public/cpp/system/platform_handle.h"
#include "mojo/public/cpp/system/message_pipe.h"
#include "mojo/public/cpp/system/data_pipe.h"
#include "mojo/public/cpp/system/buffer.h"

#include <array>
#include <cstdint>
#include <cstring>
#include <limits>
#include <functional>
#include <optional>
#include <string>
#include <unordered_map>
#include <utility>
#include <vector>

#include "uuid_gen.h"
#include "code_injection_gen.h"
#include "context_type_gen.h"
#include "extra_response_data_gen.h"
#include "host_id_gen.h"
#include "injection_type_gen.h"
#include "extension_id_gen.h"
#include "match_origin_as_fallback_gen.h"
#include "message_port_gen.h"
#include "run_location_gen.h"
#include "stack_frame_gen.h"
#include "view_type_gen.h"
#include "string16_gen.h"
#include "values_gen.h"
#include "geometry_gen.h"
#include "url_gen.h"
#include "console_message_gen.h"

#ifndef MOJO_NATIVE_TRAITS_DEFINED
#define MOJO_NATIVE_TRAITS_DEFINED
namespace mojo {
template <typename T>
struct NativeTraits {
  static void Write(Message&, const T&) = delete;
  static bool Read(const Message&, size_t*, T*) = delete;
};
}  // namespace mojo
#endif

namespace extensions {
namespace mojom {

class LocalFrame;
class LocalFrameHost;

struct ExecuteCodeParams;
struct RequestParams;

struct ExecuteCodeParams {
  extensions::mojom::HostID host_id{};
  extensions::mojom::CodeInjection injection{};
  url::mojom::Url webview_src{};
  extensions::mojom::MatchOriginAsFallbackBehavior match_origin_as_fallback_behavior{};
  extensions::mojom::RunLocation run_at{};
  bool is_web_view{};
  // Object Type Identifier: intern_key is the shape string (Go++ go/types intern);
  // type_key() is the C++ token (Go++ type_key_of<T>()); CHPT names objects
  // with the interned tag (WASMv8Bindings + WASMSafeSpace). FromHandle fails
  // unless the tag matches.
  static constexpr const char* intern_key() { return "struct:extensions.mojom.ExecuteCodeParams"; }
  static const void* type_key() { static char k; return &k; }
  static v8::CppHeapPointerTag chpt_tag() {
    return mojo::internal::TypeTag(type_key());
  }
  static v8::CppHeapPointerHandle NameOnHeap(ExecuteCodeParams* p) {
    return mojo::internal::NameObject(p, type_key());
  }
  static ExecuteCodeParams* FromHandle(v8::CppHeapPointerHandle h) {
    return static_cast<ExecuteCodeParams*>(mojo::internal::GetObject(h, type_key()));
  }
};

struct RequestParams {
  std::string name{};
  mojo_base::mojom::ListValue arguments{};
  std::string extension_id{};
  url::mojom::Url source_url{};
  network::mojom::ContextType context_type{};
  int32_t request_id{};
  bool has_callback{};
  bool user_gesture{};
  int32_t worker_thread_id{};
  int64_t service_worker_version_id{};
  std::optional<v8::internal::CageVector<extensions::mojom::StackFrame>> js_callstack{};
  // Object Type Identifier: intern_key is the shape string (Go++ go/types intern);
  // type_key() is the C++ token (Go++ type_key_of<T>()); CHPT names objects
  // with the interned tag (WASMv8Bindings + WASMSafeSpace). FromHandle fails
  // unless the tag matches.
  static constexpr const char* intern_key() { return "struct:extensions.mojom.RequestParams"; }
  static const void* type_key() { static char k; return &k; }
  static v8::CppHeapPointerTag chpt_tag() {
    return mojo::internal::TypeTag(type_key());
  }
  static v8::CppHeapPointerHandle NameOnHeap(RequestParams* p) {
    return mojo::internal::NameObject(p, type_key());
  }
  static RequestParams* FromHandle(v8::CppHeapPointerHandle h) {
    return static_cast<RequestParams*>(mojo::internal::GetObject(h, type_key()));
  }
};

void WriteExecuteCodeParams(mojo::Message& message, const ExecuteCodeParams& value);
bool ReadExecuteCodeParams(const mojo::Message& message, size_t* offset, ExecuteCodeParams* out);
void WriteRequestParams(mojo::Message& message, const RequestParams& value);
bool ReadRequestParams(const mojo::Message& message, size_t* offset, RequestParams* out);

inline void WriteExecuteCodeParams(mojo::Message& message, const ExecuteCodeParams& value) {
  size_t wvc_header_offset = message.payload_num_bytes();
  mojo::internal::WriteStructHeader(&message, 0, 0);
  extensions::mojom::WriteHostID(message, value.host_id);
  extensions::mojom::WriteCodeInjection(message, value.injection);
  url::mojom::WriteUrl(message, value.webview_src);
  mojo::internal::WriteScalar(&message, static_cast<int32_t>(value.match_origin_as_fallback_behavior));
  mojo::internal::WriteScalar(&message, static_cast<int32_t>(value.run_at));
  mojo::internal::WriteScalar(&message, value.is_web_view);
  mojo::internal::PatchStructHeader(
      message.mutable_payload() + wvc_header_offset,
      static_cast<uint32_t>(message.payload_num_bytes() - wvc_header_offset),
      0u);
}

inline bool ReadExecuteCodeParams(const mojo::Message& message, size_t* offset, ExecuteCodeParams* out) {
  uint32_t wvc_num_bytes = 0;
  uint32_t wvc_version = 0;
  if (!mojo::internal::ReadStructHeader(message, offset, &wvc_num_bytes, &wvc_version)) {
    return false;
  }
  if (wvc_num_bytes < 8u) return false;
  size_t wvc_struct_end =
      *offset - 8u + wvc_num_bytes;
  if (wvc_struct_end > message.payload_num_bytes()) return false;
  if (!extensions::mojom::ReadHostID(message, offset, &(out->host_id))) return false;
  if (!extensions::mojom::ReadCodeInjection(message, offset, &(out->injection))) return false;
  if (!url::mojom::ReadUrl(message, offset, &(out->webview_src))) return false;
  int32_t wvc_v0 = 0;
  if (!mojo::internal::ReadScalar(message, offset, &wvc_v0)) return false;
  if (!extensions::mojom::IsKnownMatchOriginAsFallbackBehaviorAsOf(wvc_v0, wvc_version)) return false;
  out->match_origin_as_fallback_behavior = static_cast<extensions::mojom::MatchOriginAsFallbackBehavior>(wvc_v0);
  int32_t wvc_v1 = 0;
  if (!mojo::internal::ReadScalar(message, offset, &wvc_v1)) return false;
  if (!extensions::mojom::IsKnownRunLocationAsOf(wvc_v1, wvc_version)) return false;
  out->run_at = static_cast<extensions::mojom::RunLocation>(wvc_v1);
  if (!mojo::internal::ReadScalar(message, offset, &(out->is_web_view))) return false;
  *offset = wvc_struct_end;
  return true;
}

inline void WriteRequestParams(mojo::Message& message, const RequestParams& value) {
  size_t wvc_header_offset = message.payload_num_bytes();
  mojo::internal::WriteStructHeader(&message, 0, 0);
  mojo::internal::WriteString(&message, value.name);
  mojo_base::mojom::WriteListValue(message, value.arguments);
  mojo::internal::WriteString(&message, value.extension_id);
  url::mojom::WriteUrl(message, value.source_url);
  mojo::internal::WriteScalar(&message, static_cast<int32_t>(value.context_type));
  mojo::internal::WriteScalar(&message, value.request_id);
  mojo::internal::WriteScalar(&message, value.has_callback);
  mojo::internal::WriteScalar(&message, value.user_gesture);
  mojo::internal::WriteScalar(&message, value.worker_thread_id);
  mojo::internal::WriteScalar(&message, value.service_worker_version_id);
  {
    bool wvc_has0 = value.js_callstack.has_value();
    mojo::internal::WriteScalar(&message, wvc_has0);
    if (wvc_has0) {
      {
        uint32_t wvc_n1 = static_cast<uint32_t>((*value.js_callstack).size());
        message.WritePayload(&wvc_n1, sizeof(wvc_n1));
        for (const auto& wvc_e1 : (*value.js_callstack)) {
          extensions::mojom::WriteStackFrame(message, wvc_e1);
        }
      }
    }
  }
  mojo::internal::PatchStructHeader(
      message.mutable_payload() + wvc_header_offset,
      static_cast<uint32_t>(message.payload_num_bytes() - wvc_header_offset),
      0u);
}

inline bool ReadRequestParams(const mojo::Message& message, size_t* offset, RequestParams* out) {
  uint32_t wvc_num_bytes = 0;
  uint32_t wvc_version = 0;
  if (!mojo::internal::ReadStructHeader(message, offset, &wvc_num_bytes, &wvc_version)) {
    return false;
  }
  if (wvc_num_bytes < 8u) return false;
  size_t wvc_struct_end =
      *offset - 8u + wvc_num_bytes;
  if (wvc_struct_end > message.payload_num_bytes()) return false;
  if (!mojo::internal::ReadString(message, offset, &(out->name))) return false;
  if (!mojo_base::mojom::ReadListValue(message, offset, &(out->arguments))) return false;
  if (!mojo::internal::ReadString(message, offset, &(out->extension_id))) return false;
  if (!url::mojom::ReadUrl(message, offset, &(out->source_url))) return false;
  int32_t wvc_v0 = 0;
  if (!mojo::internal::ReadScalar(message, offset, &wvc_v0)) return false;
  if (!network::mojom::IsKnownContextTypeAsOf(wvc_v0, wvc_version)) return false;
  out->context_type = static_cast<network::mojom::ContextType>(wvc_v0);
  if (!mojo::internal::ReadScalar(message, offset, &(out->request_id))) return false;
  if (!mojo::internal::ReadScalar(message, offset, &(out->has_callback))) return false;
  if (!mojo::internal::ReadScalar(message, offset, &(out->user_gesture))) return false;
  if (!mojo::internal::ReadScalar(message, offset, &(out->worker_thread_id))) return false;
  if (!mojo::internal::ReadScalar(message, offset, &(out->service_worker_version_id))) return false;
  {
    bool wvc_has1 = false;
    if (!mojo::internal::ReadScalar(message, offset, &wvc_has1)) return false;
    if (wvc_has1) {
      v8::internal::CageVector<extensions::mojom::StackFrame> wvc_opt1{};
      {
        uint32_t wvc_n2 = 0;
        if (!mojo::internal::ReadScalar(message, offset, &wvc_n2)) return false;
        (wvc_opt1).resize(wvc_n2);
        for (uint32_t wvc_i2 = 0; wvc_i2 < wvc_n2; ++wvc_i2) {
          if (!extensions::mojom::ReadStackFrame(message, offset, &((wvc_opt1)[wvc_i2]))) return false;
        }
      }
      out->js_callstack = std::move(wvc_opt1);
    } else {
      out->js_callstack = std::nullopt;
    }
  }
  *offset = wvc_struct_end;
  return true;
}

class LocalFrame {
 public:
  virtual ~LocalFrame() = default;
  virtual void SetFrameName(const std::string& frame_name) = 0;
  virtual void SetSpatialNavigationEnabled(bool spatial_nav_enabled) = 0;
  virtual void SetTabId(int32_t tab_id) = 0;
  virtual void AppWindowClosed(bool send_onclosed) = 0;
  virtual void NotifyRenderViewType(extensions::mojom::ViewType view_type) = 0;
  virtual void MessageInvoke(const extensions::mojom::ExtensionId& extension_id, const std::string& module_name, const std::string& function_name, const mojo_base::mojom::ListValue& args) = 0;
  virtual void ExecuteCode(const ExecuteCodeParams& param, base::OnceCallback<void(std::string, url::mojom::Url, std::optional<mojo_base::mojom::Value>)> callback) = 0;
  virtual void ExecuteDeclarativeScript(int32_t tab_id, const extensions::mojom::ExtensionId& extension_id, const std::string& script_id, const url::mojom::Url& url) = 0;
  virtual void UpdateBrowserWindowId(int32_t window_id) = 0;
  virtual void DispatchOnConnect(const extensions::mojom::PortId& port_id, extensions::mojom::ChannelType channel_type, const std::string& channel_name, const extensions::mojom::TabConnectionInfo& tab_info, const extensions::mojom::ExternalConnectionInfo& external_connection_info, mojo::PendingAssociatedReceiver<extensions::mojom::MessagePort> port, mojo::PendingAssociatedRemote<extensions::mojom::MessagePortHost> port_host, base::OnceCallback<void(bool)> callback) = 0;

  static constexpr uint32_t kSetFrameNameName = 0;
  static constexpr uint32_t kSetSpatialNavigationEnabledName = 1;
  static constexpr uint32_t kSetTabIdName = 2;
  static constexpr uint32_t kAppWindowClosedName = 3;
  static constexpr uint32_t kNotifyRenderViewTypeName = 4;
  static constexpr uint32_t kMessageInvokeName = 5;
  static constexpr uint32_t kExecuteCodeName = 6;
  static constexpr uint32_t kExecuteDeclarativeScriptName = 7;
  static constexpr uint32_t kUpdateBrowserWindowIdName = 8;
  static constexpr uint32_t kDispatchOnConnectName = 9;
  static constexpr uint32_t kVersion = 0u;

  // Object Type Identifier: intern_key is the shape string (Go++ go/types intern);
  // type_key() is the C++ token (Go++ type_key_of<T>()); CHPT names objects
  // with the interned tag (WASMv8Bindings + WASMSafeSpace). FromHandle fails
  // unless the tag matches.
  static constexpr const char* intern_key() { return "interface:extensions.mojom.LocalFrame"; }
  static const void* type_key() { static char k; return &k; }
  static v8::CppHeapPointerTag chpt_tag() {
    return mojo::internal::TypeTag(type_key());
  }
  static v8::CppHeapPointerHandle NameOnHeap(LocalFrame* p) {
    return mojo::internal::NameObject(p, type_key());
  }
  static LocalFrame* FromHandle(v8::CppHeapPointerHandle h) {
    return static_cast<LocalFrame*>(mojo::internal::GetObject(h, type_key()));
  }
  class Proxy_;  // defined below, once LocalFrame is a complete type

  class Stub_ : public mojo::MessageReceiver {
   public:
    Stub_(LocalFrame* impl,
          mojo::MultiplexRouter* router,
          mojo::InterfaceId id = mojo::kPrimaryInterfaceId)
        : impl_(impl), router_(router), id_(id) {}

    [[nodiscard]] bool Accept(mojo::Message* message) override {
      if (message->name() == mojo::internal::kRunMessageId) {
        return mojo::internal::HandleQueryVersionMessage(
            message, router_, id_, kVersion);
      }
      if (message->name() == mojo::internal::kRunOrClosePipeMessageId) {
        return mojo::internal::HandleRequireVersionMessage(
            *message, kVersion);
      }
      if (message->name() == kSetFrameNameName) return AcceptSetFrameName(message);
      if (message->name() == kSetSpatialNavigationEnabledName) return AcceptSetSpatialNavigationEnabled(message);
      if (message->name() == kSetTabIdName) return AcceptSetTabId(message);
      if (message->name() == kAppWindowClosedName) return AcceptAppWindowClosed(message);
      if (message->name() == kNotifyRenderViewTypeName) return AcceptNotifyRenderViewType(message);
      if (message->name() == kMessageInvokeName) return AcceptMessageInvoke(message);
      if (message->name() == kExecuteCodeName) return AcceptExecuteCode(message);
      if (message->name() == kExecuteDeclarativeScriptName) return AcceptExecuteDeclarativeScript(message);
      if (message->name() == kUpdateBrowserWindowIdName) return AcceptUpdateBrowserWindowId(message);
      if (message->name() == kDispatchOnConnectName) return AcceptDispatchOnConnect(message);
      return false;
    }

   private:
    bool AcceptSetFrameName(mojo::Message* message) {
      size_t offset = 0;
      std::string frame_name{};
      if (!mojo::internal::ReadString(*message, &offset, &(frame_name))) return false;
      impl_->SetFrameName(frame_name);
      return true;
    }

    bool AcceptSetSpatialNavigationEnabled(mojo::Message* message) {
      size_t offset = 0;
      bool spatial_nav_enabled{};
      if (!mojo::internal::ReadScalar(*message, &offset, &(spatial_nav_enabled))) return false;
      impl_->SetSpatialNavigationEnabled(spatial_nav_enabled);
      return true;
    }

    bool AcceptSetTabId(mojo::Message* message) {
      size_t offset = 0;
      int32_t tab_id{};
      if (!mojo::internal::ReadScalar(*message, &offset, &(tab_id))) return false;
      impl_->SetTabId(tab_id);
      return true;
    }

    bool AcceptAppWindowClosed(mojo::Message* message) {
      size_t offset = 0;
      bool send_onclosed{};
      if (!mojo::internal::ReadScalar(*message, &offset, &(send_onclosed))) return false;
      impl_->AppWindowClosed(send_onclosed);
      return true;
    }

    bool AcceptNotifyRenderViewType(mojo::Message* message) {
      size_t offset = 0;
      extensions::mojom::ViewType view_type{};
      int32_t wvc_v0 = 0;
      if (!mojo::internal::ReadScalar(*message, &offset, &wvc_v0)) return false;
      if (!extensions::mojom::IsKnownViewType(wvc_v0)) return false;
      view_type = static_cast<extensions::mojom::ViewType>(wvc_v0);
      impl_->NotifyRenderViewType(view_type);
      return true;
    }

    bool AcceptMessageInvoke(mojo::Message* message) {
      size_t offset = 0;
      extensions::mojom::ExtensionId extension_id{};
      if (!extensions::mojom::ReadExtensionId(*message, &offset, &(extension_id))) return false;
      std::string module_name{};
      if (!mojo::internal::ReadString(*message, &offset, &(module_name))) return false;
      std::string function_name{};
      if (!mojo::internal::ReadString(*message, &offset, &(function_name))) return false;
      mojo_base::mojom::ListValue args{};
      if (!mojo_base::mojom::ReadListValue(*message, &offset, &(args))) return false;
      impl_->MessageInvoke(extension_id, module_name, function_name, args);
      return true;
    }

    bool AcceptExecuteCode(mojo::Message* message) {
      size_t offset = 0;
      ExecuteCodeParams param{};
      if (!ReadExecuteCodeParams(*message, &offset, &(param))) return false;
      const uint64_t request_id = message->request_id();
      mojo::MultiplexRouter* router = router_;
      const mojo::InterfaceId id = id_;
      impl_->ExecuteCode(param, [router, id, request_id](std::string error, url::mojom::Url url, std::optional<mojo_base::mojom::Value> result) {
        mojo::Message response(LocalFrame::kExecuteCodeName, mojo::Message::kFlagIsResponse, id);
        response.set_request_id(request_id);
        mojo::internal::WriteString(&response, error);
        url::mojom::WriteUrl(response, url);
        {
          bool wvc_has0 = result.has_value();
          mojo::internal::WriteScalar(&response, wvc_has0);
          if (wvc_has0) {
            mojo_base::mojom::WriteValue(response, (*result));
          }
        }
        (void)router->SendMessage(&response);
      });
      return true;
    }

    bool AcceptExecuteDeclarativeScript(mojo::Message* message) {
      size_t offset = 0;
      int32_t tab_id{};
      if (!mojo::internal::ReadScalar(*message, &offset, &(tab_id))) return false;
      extensions::mojom::ExtensionId extension_id{};
      if (!extensions::mojom::ReadExtensionId(*message, &offset, &(extension_id))) return false;
      std::string script_id{};
      if (!mojo::internal::ReadString(*message, &offset, &(script_id))) return false;
      url::mojom::Url url{};
      if (!url::mojom::ReadUrl(*message, &offset, &(url))) return false;
      impl_->ExecuteDeclarativeScript(tab_id, extension_id, script_id, url);
      return true;
    }

    bool AcceptUpdateBrowserWindowId(mojo::Message* message) {
      size_t offset = 0;
      int32_t window_id{};
      if (!mojo::internal::ReadScalar(*message, &offset, &(window_id))) return false;
      impl_->UpdateBrowserWindowId(window_id);
      return true;
    }

    bool AcceptDispatchOnConnect(mojo::Message* message) {
      size_t offset = 0;
      std::vector<mojo::ScopedHandle> wvc_handles_store = message->TakeHandles();
      std::vector<mojo::ScopedHandle>* wvc_handles = &wvc_handles_store;
      size_t wvc_handle_idx_store = 0;
      size_t* wvc_handle_idx = &wvc_handle_idx_store;
      mojo::MultiplexRouter* router = router_;
      extensions::mojom::PortId port_id{};
      if (!extensions::mojom::ReadPortId(*message, &offset, &(port_id))) return false;
      extensions::mojom::ChannelType channel_type{};
      int32_t wvc_v0 = 0;
      if (!mojo::internal::ReadScalar(*message, &offset, &wvc_v0)) return false;
      if (!extensions::mojom::IsKnownChannelType(wvc_v0)) return false;
      channel_type = static_cast<extensions::mojom::ChannelType>(wvc_v0);
      std::string channel_name{};
      if (!mojo::internal::ReadString(*message, &offset, &(channel_name))) return false;
      extensions::mojom::TabConnectionInfo tab_info{};
      if (!extensions::mojom::ReadTabConnectionInfo(*message, &offset, &(tab_info))) return false;
      extensions::mojom::ExternalConnectionInfo external_connection_info{};
      if (!extensions::mojom::ReadExternalConnectionInfo(*message, &offset, &(external_connection_info))) return false;
      uint32_t port_iid = 0;
      if (!mojo::internal::ReadScalar(*message, &offset, &port_iid)) return false;
      mojo::PendingAssociatedReceiver<extensions::mojom::MessagePort> port(router->CreateLocalEndpointHandle(port_iid));
      uint32_t port_host_iid = 0;
      uint32_t port_host_version = 0;
      if (!mojo::internal::ReadScalar(*message, &offset, &port_host_iid)) return false;
      if (!mojo::internal::ReadScalar(*message, &offset, &port_host_version)) return false;
      mojo::PendingAssociatedRemote<extensions::mojom::MessagePortHost> port_host(router->CreateLocalEndpointHandle(port_host_iid), port_host_version);
      const uint64_t request_id = message->request_id();
      const mojo::InterfaceId id = id_;
      impl_->DispatchOnConnect(port_id, channel_type, channel_name, tab_info, external_connection_info, std::move(port), std::move(port_host), [router, id, request_id](bool success) {
        mojo::Message response(LocalFrame::kDispatchOnConnectName, mojo::Message::kFlagIsResponse, id);
        response.set_request_id(request_id);
        mojo::internal::WriteScalar(&response, success);
        (void)router->SendMessage(&response);
      });
      return true;
    }

    LocalFrame* impl_;
    mojo::MultiplexRouter* router_;
    mojo::InterfaceId id_;
  };
};

class LocalFrame::Proxy_ : public LocalFrame, public mojo::MessageReceiver {
 public:
  explicit Proxy_(mojo::MultiplexRouter* router,
                   mojo::InterfaceId id = mojo::kPrimaryInterfaceId)
      : router_(router), id_(id) {}

  void SetFrameName(const std::string& frame_name) override {
    mojo::Message message(kSetFrameNameName, 0, id_);
    mojo::internal::WriteString(&message, frame_name);
    (void)router_->SendMessage(&message);
  }

  void SetSpatialNavigationEnabled(bool spatial_nav_enabled) override {
    mojo::Message message(kSetSpatialNavigationEnabledName, 0, id_);
    mojo::internal::WriteScalar(&message, spatial_nav_enabled);
    (void)router_->SendMessage(&message);
  }

  void SetTabId(int32_t tab_id) override {
    mojo::Message message(kSetTabIdName, 0, id_);
    mojo::internal::WriteScalar(&message, tab_id);
    (void)router_->SendMessage(&message);
  }

  void AppWindowClosed(bool send_onclosed) override {
    mojo::Message message(kAppWindowClosedName, 0, id_);
    mojo::internal::WriteScalar(&message, send_onclosed);
    (void)router_->SendMessage(&message);
  }

  void NotifyRenderViewType(extensions::mojom::ViewType view_type) override {
    mojo::Message message(kNotifyRenderViewTypeName, 0, id_);
    mojo::internal::WriteScalar(&message, static_cast<int32_t>(view_type));
    (void)router_->SendMessage(&message);
  }

  void MessageInvoke(const extensions::mojom::ExtensionId& extension_id, const std::string& module_name, const std::string& function_name, const mojo_base::mojom::ListValue& args) override {
    mojo::Message message(kMessageInvokeName, 0, id_);
    extensions::mojom::WriteExtensionId(message, extension_id);
    mojo::internal::WriteString(&message, module_name);
    mojo::internal::WriteString(&message, function_name);
    mojo_base::mojom::WriteListValue(message, args);
    (void)router_->SendMessage(&message);
  }

  void ExecuteCode(const ExecuteCodeParams& param, base::OnceCallback<void(std::string, url::mojom::Url, std::optional<mojo_base::mojom::Value>)> callback) override {
    uint64_t request_id = responses_.RegisterPendingResponse(
        [callback = std::move(callback)](mojo::Message* response) mutable {
          size_t offset = 0;
          std::string error{};
          if (!mojo::internal::ReadString(*response, &offset, &(error))) return false;
          url::mojom::Url url{};
          if (!url::mojom::ReadUrl(*response, &offset, &(url))) return false;
          std::optional<mojo_base::mojom::Value> result{};
          {
            bool wvc_has0 = false;
            if (!mojo::internal::ReadScalar(*response, &offset, &wvc_has0)) return false;
            if (wvc_has0) {
              mojo_base::mojom::Value wvc_opt0{};
              if (!mojo_base::mojom::ReadValue(*response, &offset, &(wvc_opt0))) return false;
              result = std::move(wvc_opt0);
            } else {
              result = std::nullopt;
            }
          }
          std::move(callback).Run(error, url, result);
          return true;
        });
    mojo::Message message(kExecuteCodeName, mojo::Message::kFlagExpectsResponse, id_);
    message.set_request_id(request_id);
    WriteExecuteCodeParams(message, param);
    (void)router_->SendMessage(&message);
  }

  void ExecuteDeclarativeScript(int32_t tab_id, const extensions::mojom::ExtensionId& extension_id, const std::string& script_id, const url::mojom::Url& url) override {
    mojo::Message message(kExecuteDeclarativeScriptName, 0, id_);
    mojo::internal::WriteScalar(&message, tab_id);
    extensions::mojom::WriteExtensionId(message, extension_id);
    mojo::internal::WriteString(&message, script_id);
    url::mojom::WriteUrl(message, url);
    (void)router_->SendMessage(&message);
  }

  void UpdateBrowserWindowId(int32_t window_id) override {
    mojo::Message message(kUpdateBrowserWindowIdName, 0, id_);
    mojo::internal::WriteScalar(&message, window_id);
    (void)router_->SendMessage(&message);
  }

  void DispatchOnConnect(const extensions::mojom::PortId& port_id, extensions::mojom::ChannelType channel_type, const std::string& channel_name, const extensions::mojom::TabConnectionInfo& tab_info, const extensions::mojom::ExternalConnectionInfo& external_connection_info, mojo::PendingAssociatedReceiver<extensions::mojom::MessagePort> port, mojo::PendingAssociatedRemote<extensions::mojom::MessagePortHost> port_host, base::OnceCallback<void(bool)> callback) override {
    uint64_t request_id = responses_.RegisterPendingResponse(
        [callback = std::move(callback)](mojo::Message* response) mutable {
          size_t offset = 0;
          bool success{};
          if (!mojo::internal::ReadScalar(*response, &offset, &(success))) return false;
          std::move(callback).Run(success);
          return true;
        });
    mojo::ScopedInterfaceEndpointHandle port_handle = port.PassHandle();
    uint32_t port_iid = port_handle.ReleaseWithoutClosing();
    uint32_t port_host_version = port_host.version();
    mojo::ScopedInterfaceEndpointHandle port_host_handle = port_host.PassHandle();
    uint32_t port_host_iid = port_host_handle.ReleaseWithoutClosing();
    mojo::Message message(kDispatchOnConnectName, mojo::Message::kFlagExpectsResponse, id_);
    message.set_request_id(request_id);
    extensions::mojom::WritePortId(message, port_id);
    mojo::internal::WriteScalar(&message, static_cast<int32_t>(channel_type));
    mojo::internal::WriteString(&message, channel_name);
    extensions::mojom::WriteTabConnectionInfo(message, tab_info);
    extensions::mojom::WriteExternalConnectionInfo(message, external_connection_info);
    message.WritePayload(&port_iid, sizeof(port_iid));
    message.WritePayload(&port_host_iid, sizeof(port_host_iid));
    message.WritePayload(&port_host_version, sizeof(port_host_version));
    (void)router_->SendMessage(&message);
  }

  void QueryVersion(base::OnceCallback<void(uint32_t)> callback) {
    uint64_t request_id = responses_.RegisterPendingResponse(
        [callback = std::move(callback)](mojo::Message* response) mutable {
          size_t offset = 0;
          uint32_t tag = 0;
          uint32_t version = 0;
          if (!mojo::internal::ReadScalar(*response, &offset, &tag) ||
              tag != mojo::internal::kRunQueryVersionResult ||
              !mojo::internal::ReadScalar(*response, &offset, &version)) {
            return false;
          }
          std::move(callback).Run(version);
          return true;
        });
    mojo::Message message(mojo::internal::kRunMessageId,
                          mojo::Message::kFlagExpectsResponse, id_);
    message.set_request_id(request_id);
    mojo::internal::WriteScalar(&message, mojo::internal::kRunQueryVersion);
    (void)router_->SendMessage(&message);
  }

  void RequireVersion(uint32_t version) {
    mojo::Message message(mojo::internal::kRunOrClosePipeMessageId, 0, id_);
    mojo::internal::WriteScalar(&message, mojo::internal::kRunRequireVersion);
    mojo::internal::WriteScalar(&message, version);
    (void)router_->SendMessage(&message);
  }

  [[nodiscard]] bool Accept(mojo::Message* message) override {
    if (!message->has_flag(mojo::Message::kFlagIsResponse)) {
      return false;
    }
    return responses_.DispatchResponse(message);
  }

 private:
  mojo::MultiplexRouter* router_;
  mojo::InterfaceId id_;
  mojo::internal::ResponseDispatcher responses_;
};

class LocalFrameHost {
 public:
  virtual ~LocalFrameHost() = default;
  virtual void RequestScriptInjectionPermission(const extensions::mojom::ExtensionId& extension_id, extensions::mojom::InjectionType script_type, extensions::mojom::RunLocation run_location, base::OnceCallback<void(bool)> callback) = 0;
  virtual void GetAppInstallState(const url::mojom::Url& url, base::OnceCallback<void(std::string)> callback) = 0;
  virtual void Request(const RequestParams& params, base::OnceCallback<void(bool, mojo_base::mojom::ListValue, std::string, std::optional<extensions::mojom::ExtraResponseData>)> callback) = 0;
  virtual void ResponseAck(const mojo_base::mojom::Uuid& request_uuid) = 0;
  virtual void WatchedPageChange(const v8::internal::CageVector<std::string>& css_selectors) = 0;
  virtual void DetailedConsoleMessageAdded(const mojo_base::mojom::String16& message, const mojo_base::mojom::String16& source, const v8::internal::CageVector<extensions::mojom::StackFrame>& stack_trace, blink::mojom::ConsoleMessageLevel level) = 0;
  virtual void ContentScriptsExecuting(const v8::internal::CageMap<std::string, v8::internal::CageVector<std::string>>& extension_id_to_scripts, const url::mojom::Url& frame_url) = 0;
  virtual void IncrementLazyKeepaliveCount() = 0;
  virtual void DecrementLazyKeepaliveCount() = 0;
  virtual void AppWindowReady() = 0;
  virtual void OpenChannelToExtension(const extensions::mojom::ExternalConnectionInfo& info, extensions::mojom::ChannelType channel_type, const std::string& channel_name, const extensions::mojom::PortId& port_id, mojo::PendingAssociatedRemote<extensions::mojom::MessagePort> port, mojo::PendingAssociatedReceiver<extensions::mojom::MessagePortHost> port_host) = 0;
  virtual void OpenChannelToNativeApp(const std::string& native_app_name, const v8::internal::CageVector<std::array<uint8_t, 32>>& android_certificates, const extensions::mojom::PortId& port_id, mojo::PendingAssociatedRemote<extensions::mojom::MessagePort> port, mojo::PendingAssociatedReceiver<extensions::mojom::MessagePortHost> port_host) = 0;
  virtual void OpenChannelToTab(int32_t tab_id, int32_t frame_id, const std::optional<std::string>& document_id, extensions::mojom::ChannelType channel_type, const std::string& channel_name, const extensions::mojom::PortId& port_id, mojo::PendingAssociatedRemote<extensions::mojom::MessagePort> port, mojo::PendingAssociatedReceiver<extensions::mojom::MessagePortHost> port_host) = 0;

  static constexpr uint32_t kRequestScriptInjectionPermissionName = 0;
  static constexpr uint32_t kGetAppInstallStateName = 1;
  static constexpr uint32_t kRequestName = 2;
  static constexpr uint32_t kResponseAckName = 3;
  static constexpr uint32_t kWatchedPageChangeName = 4;
  static constexpr uint32_t kDetailedConsoleMessageAddedName = 5;
  static constexpr uint32_t kContentScriptsExecutingName = 6;
  static constexpr uint32_t kIncrementLazyKeepaliveCountName = 7;
  static constexpr uint32_t kDecrementLazyKeepaliveCountName = 8;
  static constexpr uint32_t kAppWindowReadyName = 9;
  static constexpr uint32_t kOpenChannelToExtensionName = 10;
  static constexpr uint32_t kOpenChannelToNativeAppName = 11;
  static constexpr uint32_t kOpenChannelToTabName = 12;
  static constexpr uint32_t kVersion = 0u;

  // Object Type Identifier: intern_key is the shape string (Go++ go/types intern);
  // type_key() is the C++ token (Go++ type_key_of<T>()); CHPT names objects
  // with the interned tag (WASMv8Bindings + WASMSafeSpace). FromHandle fails
  // unless the tag matches.
  static constexpr const char* intern_key() { return "interface:extensions.mojom.LocalFrameHost"; }
  static const void* type_key() { static char k; return &k; }
  static v8::CppHeapPointerTag chpt_tag() {
    return mojo::internal::TypeTag(type_key());
  }
  static v8::CppHeapPointerHandle NameOnHeap(LocalFrameHost* p) {
    return mojo::internal::NameObject(p, type_key());
  }
  static LocalFrameHost* FromHandle(v8::CppHeapPointerHandle h) {
    return static_cast<LocalFrameHost*>(mojo::internal::GetObject(h, type_key()));
  }
  class Proxy_;  // defined below, once LocalFrameHost is a complete type

  class Stub_ : public mojo::MessageReceiver {
   public:
    Stub_(LocalFrameHost* impl,
          mojo::MultiplexRouter* router,
          mojo::InterfaceId id = mojo::kPrimaryInterfaceId)
        : impl_(impl), router_(router), id_(id) {}

    [[nodiscard]] bool Accept(mojo::Message* message) override {
      if (message->name() == mojo::internal::kRunMessageId) {
        return mojo::internal::HandleQueryVersionMessage(
            message, router_, id_, kVersion);
      }
      if (message->name() == mojo::internal::kRunOrClosePipeMessageId) {
        return mojo::internal::HandleRequireVersionMessage(
            *message, kVersion);
      }
      if (message->name() == kRequestScriptInjectionPermissionName) return AcceptRequestScriptInjectionPermission(message);
      if (message->name() == kGetAppInstallStateName) return AcceptGetAppInstallState(message);
      if (message->name() == kRequestName) return AcceptRequest(message);
      if (message->name() == kResponseAckName) return AcceptResponseAck(message);
      if (message->name() == kWatchedPageChangeName) return AcceptWatchedPageChange(message);
      if (message->name() == kDetailedConsoleMessageAddedName) return AcceptDetailedConsoleMessageAdded(message);
      if (message->name() == kContentScriptsExecutingName) return AcceptContentScriptsExecuting(message);
      if (message->name() == kIncrementLazyKeepaliveCountName) return AcceptIncrementLazyKeepaliveCount(message);
      if (message->name() == kDecrementLazyKeepaliveCountName) return AcceptDecrementLazyKeepaliveCount(message);
      if (message->name() == kAppWindowReadyName) return AcceptAppWindowReady(message);
      if (message->name() == kOpenChannelToExtensionName) return AcceptOpenChannelToExtension(message);
      if (message->name() == kOpenChannelToNativeAppName) return AcceptOpenChannelToNativeApp(message);
      if (message->name() == kOpenChannelToTabName) return AcceptOpenChannelToTab(message);
      return false;
    }

   private:
    bool AcceptRequestScriptInjectionPermission(mojo::Message* message) {
      size_t offset = 0;
      extensions::mojom::ExtensionId extension_id{};
      if (!extensions::mojom::ReadExtensionId(*message, &offset, &(extension_id))) return false;
      extensions::mojom::InjectionType script_type{};
      int32_t wvc_v0 = 0;
      if (!mojo::internal::ReadScalar(*message, &offset, &wvc_v0)) return false;
      if (!extensions::mojom::IsKnownInjectionType(wvc_v0)) return false;
      script_type = static_cast<extensions::mojom::InjectionType>(wvc_v0);
      extensions::mojom::RunLocation run_location{};
      int32_t wvc_v1 = 0;
      if (!mojo::internal::ReadScalar(*message, &offset, &wvc_v1)) return false;
      if (!extensions::mojom::IsKnownRunLocation(wvc_v1)) return false;
      run_location = static_cast<extensions::mojom::RunLocation>(wvc_v1);
      const uint64_t request_id = message->request_id();
      mojo::MultiplexRouter* router = router_;
      const mojo::InterfaceId id = id_;
      impl_->RequestScriptInjectionPermission(extension_id, script_type, run_location, [router, id, request_id](bool granted) {
        mojo::Message response(LocalFrameHost::kRequestScriptInjectionPermissionName, mojo::Message::kFlagIsResponse, id);
        response.set_request_id(request_id);
        mojo::internal::WriteScalar(&response, granted);
        (void)router->SendMessage(&response);
      });
      return true;
    }

    bool AcceptGetAppInstallState(mojo::Message* message) {
      size_t offset = 0;
      url::mojom::Url url{};
      if (!url::mojom::ReadUrl(*message, &offset, &(url))) return false;
      const uint64_t request_id = message->request_id();
      mojo::MultiplexRouter* router = router_;
      const mojo::InterfaceId id = id_;
      impl_->GetAppInstallState(url, [router, id, request_id](std::string state) {
        mojo::Message response(LocalFrameHost::kGetAppInstallStateName, mojo::Message::kFlagIsResponse, id);
        response.set_request_id(request_id);
        mojo::internal::WriteString(&response, state);
        (void)router->SendMessage(&response);
      });
      return true;
    }

    bool AcceptRequest(mojo::Message* message) {
      size_t offset = 0;
      RequestParams params{};
      if (!ReadRequestParams(*message, &offset, &(params))) return false;
      const uint64_t request_id = message->request_id();
      mojo::MultiplexRouter* router = router_;
      const mojo::InterfaceId id = id_;
      impl_->Request(params, [router, id, request_id](bool success, mojo_base::mojom::ListValue response_wrapper, std::string error, std::optional<extensions::mojom::ExtraResponseData> extra_data) {
        mojo::Message response(LocalFrameHost::kRequestName, mojo::Message::kFlagIsResponse, id);
        response.set_request_id(request_id);
        mojo::internal::WriteScalar(&response, success);
        mojo_base::mojom::WriteListValue(response, response_wrapper);
        mojo::internal::WriteString(&response, error);
        {
          bool wvc_has0 = extra_data.has_value();
          mojo::internal::WriteScalar(&response, wvc_has0);
          if (wvc_has0) {
            extensions::mojom::WriteExtraResponseData(response, (*extra_data));
          }
        }
        (void)router->SendMessage(&response);
      });
      return true;
    }

    bool AcceptResponseAck(mojo::Message* message) {
      size_t offset = 0;
      mojo_base::mojom::Uuid request_uuid{};
      if (!mojo_base::mojom::ReadUuid(*message, &offset, &(request_uuid))) return false;
      impl_->ResponseAck(request_uuid);
      return true;
    }

    bool AcceptWatchedPageChange(mojo::Message* message) {
      size_t offset = 0;
      v8::internal::CageVector<std::string> css_selectors{};
      {
        uint32_t wvc_n0 = 0;
        if (!mojo::internal::ReadScalar(*message, &offset, &wvc_n0)) return false;
        (css_selectors).resize(wvc_n0);
        for (uint32_t wvc_i0 = 0; wvc_i0 < wvc_n0; ++wvc_i0) {
          if (!mojo::internal::ReadString(*message, &offset, &((css_selectors)[wvc_i0]))) return false;
        }
      }
      impl_->WatchedPageChange(css_selectors);
      return true;
    }

    bool AcceptDetailedConsoleMessageAdded(mojo::Message* message) {
      size_t offset = 0;
      mojo_base::mojom::String16 message{};
      if (!mojo_base::mojom::ReadString16(*message, &offset, &(message))) return false;
      mojo_base::mojom::String16 source{};
      if (!mojo_base::mojom::ReadString16(*message, &offset, &(source))) return false;
      v8::internal::CageVector<extensions::mojom::StackFrame> stack_trace{};
      {
        uint32_t wvc_n0 = 0;
        if (!mojo::internal::ReadScalar(*message, &offset, &wvc_n0)) return false;
        (stack_trace).resize(wvc_n0);
        for (uint32_t wvc_i0 = 0; wvc_i0 < wvc_n0; ++wvc_i0) {
          if (!extensions::mojom::ReadStackFrame(*message, &offset, &((stack_trace)[wvc_i0]))) return false;
        }
      }
      blink::mojom::ConsoleMessageLevel level{};
      int32_t wvc_v1 = 0;
      if (!mojo::internal::ReadScalar(*message, &offset, &wvc_v1)) return false;
      if (!blink::mojom::IsKnownConsoleMessageLevel(wvc_v1)) return false;
      level = static_cast<blink::mojom::ConsoleMessageLevel>(wvc_v1);
      impl_->DetailedConsoleMessageAdded(message, source, stack_trace, level);
      return true;
    }

    bool AcceptContentScriptsExecuting(mojo::Message* message) {
      size_t offset = 0;
      v8::internal::CageMap<std::string, v8::internal::CageVector<std::string>> extension_id_to_scripts{};
      {
        uint32_t wvc_n0 = 0;
        if (!mojo::internal::ReadScalar(*message, &offset, &wvc_n0)) return false;
        (extension_id_to_scripts).clear();
        for (uint32_t wvc_i0 = 0; wvc_i0 < wvc_n0; ++wvc_i0) {
          std::string wvc_k0{};
          if (!mojo::internal::ReadString(*message, &offset, &(wvc_k0))) return false;
          v8::internal::CageVector<std::string> wvc_v0{};
          {
            uint32_t wvc_n1 = 0;
            if (!mojo::internal::ReadScalar(*message, &offset, &wvc_n1)) return false;
            (wvc_v0).resize(wvc_n1);
            for (uint32_t wvc_i1 = 0; wvc_i1 < wvc_n1; ++wvc_i1) {
              if (!mojo::internal::ReadString(*message, &offset, &((wvc_v0)[wvc_i1]))) return false;
            }
          }
          (extension_id_to_scripts).emplace(std::move(wvc_k0), std::move(wvc_v0));
        }
      }
      url::mojom::Url frame_url{};
      if (!url::mojom::ReadUrl(*message, &offset, &(frame_url))) return false;
      impl_->ContentScriptsExecuting(extension_id_to_scripts, frame_url);
      return true;
    }

    bool AcceptIncrementLazyKeepaliveCount(mojo::Message* message) {
      size_t offset = 0;
      (void)message;
      (void)offset;
      impl_->IncrementLazyKeepaliveCount();
      return true;
    }

    bool AcceptDecrementLazyKeepaliveCount(mojo::Message* message) {
      size_t offset = 0;
      (void)message;
      (void)offset;
      impl_->DecrementLazyKeepaliveCount();
      return true;
    }

    bool AcceptAppWindowReady(mojo::Message* message) {
      size_t offset = 0;
      (void)message;
      (void)offset;
      impl_->AppWindowReady();
      return true;
    }

    bool AcceptOpenChannelToExtension(mojo::Message* message) {
      size_t offset = 0;
      std::vector<mojo::ScopedHandle> wvc_handles_store = message->TakeHandles();
      std::vector<mojo::ScopedHandle>* wvc_handles = &wvc_handles_store;
      size_t wvc_handle_idx_store = 0;
      size_t* wvc_handle_idx = &wvc_handle_idx_store;
      mojo::MultiplexRouter* router = router_;
      extensions::mojom::ExternalConnectionInfo info{};
      if (!extensions::mojom::ReadExternalConnectionInfo(*message, &offset, &(info))) return false;
      extensions::mojom::ChannelType channel_type{};
      int32_t wvc_v0 = 0;
      if (!mojo::internal::ReadScalar(*message, &offset, &wvc_v0)) return false;
      if (!extensions::mojom::IsKnownChannelType(wvc_v0)) return false;
      channel_type = static_cast<extensions::mojom::ChannelType>(wvc_v0);
      std::string channel_name{};
      if (!mojo::internal::ReadString(*message, &offset, &(channel_name))) return false;
      extensions::mojom::PortId port_id{};
      if (!extensions::mojom::ReadPortId(*message, &offset, &(port_id))) return false;
      uint32_t port_iid = 0;
      uint32_t port_version = 0;
      if (!mojo::internal::ReadScalar(*message, &offset, &port_iid)) return false;
      if (!mojo::internal::ReadScalar(*message, &offset, &port_version)) return false;
      mojo::PendingAssociatedRemote<extensions::mojom::MessagePort> port(router->CreateLocalEndpointHandle(port_iid), port_version);
      uint32_t port_host_iid = 0;
      if (!mojo::internal::ReadScalar(*message, &offset, &port_host_iid)) return false;
      mojo::PendingAssociatedReceiver<extensions::mojom::MessagePortHost> port_host(router->CreateLocalEndpointHandle(port_host_iid));
      impl_->OpenChannelToExtension(info, channel_type, channel_name, port_id, std::move(port), std::move(port_host));
      return true;
    }

    bool AcceptOpenChannelToNativeApp(mojo::Message* message) {
      size_t offset = 0;
      std::vector<mojo::ScopedHandle> wvc_handles_store = message->TakeHandles();
      std::vector<mojo::ScopedHandle>* wvc_handles = &wvc_handles_store;
      size_t wvc_handle_idx_store = 0;
      size_t* wvc_handle_idx = &wvc_handle_idx_store;
      mojo::MultiplexRouter* router = router_;
      std::string native_app_name{};
      if (!mojo::internal::ReadString(*message, &offset, &(native_app_name))) return false;
      v8::internal::CageVector<std::array<uint8_t, 32>> android_certificates{};
      {
        uint32_t wvc_n0 = 0;
        if (!mojo::internal::ReadScalar(*message, &offset, &wvc_n0)) return false;
        (android_certificates).resize(wvc_n0);
        for (uint32_t wvc_i0 = 0; wvc_i0 < wvc_n0; ++wvc_i0) {
          {
            for (uint32_t wvc_i1 = 0; wvc_i1 < 32u; ++wvc_i1) {
              if (!mojo::internal::ReadScalar(*message, &offset, &(((android_certificates)[wvc_i0])[wvc_i1]))) return false;
            }
          }
        }
      }
      extensions::mojom::PortId port_id{};
      if (!extensions::mojom::ReadPortId(*message, &offset, &(port_id))) return false;
      uint32_t port_iid = 0;
      uint32_t port_version = 0;
      if (!mojo::internal::ReadScalar(*message, &offset, &port_iid)) return false;
      if (!mojo::internal::ReadScalar(*message, &offset, &port_version)) return false;
      mojo::PendingAssociatedRemote<extensions::mojom::MessagePort> port(router->CreateLocalEndpointHandle(port_iid), port_version);
      uint32_t port_host_iid = 0;
      if (!mojo::internal::ReadScalar(*message, &offset, &port_host_iid)) return false;
      mojo::PendingAssociatedReceiver<extensions::mojom::MessagePortHost> port_host(router->CreateLocalEndpointHandle(port_host_iid));
      impl_->OpenChannelToNativeApp(native_app_name, android_certificates, port_id, std::move(port), std::move(port_host));
      return true;
    }

    bool AcceptOpenChannelToTab(mojo::Message* message) {
      size_t offset = 0;
      std::vector<mojo::ScopedHandle> wvc_handles_store = message->TakeHandles();
      std::vector<mojo::ScopedHandle>* wvc_handles = &wvc_handles_store;
      size_t wvc_handle_idx_store = 0;
      size_t* wvc_handle_idx = &wvc_handle_idx_store;
      mojo::MultiplexRouter* router = router_;
      int32_t tab_id{};
      if (!mojo::internal::ReadScalar(*message, &offset, &(tab_id))) return false;
      int32_t frame_id{};
      if (!mojo::internal::ReadScalar(*message, &offset, &(frame_id))) return false;
      std::optional<std::string> document_id{};
      {
        bool wvc_has0 = false;
        if (!mojo::internal::ReadScalar(*message, &offset, &wvc_has0)) return false;
        if (wvc_has0) {
          std::string wvc_opt0{};
          if (!mojo::internal::ReadString(*message, &offset, &(wvc_opt0))) return false;
          document_id = std::move(wvc_opt0);
        } else {
          document_id = std::nullopt;
        }
      }
      extensions::mojom::ChannelType channel_type{};
      int32_t wvc_v1 = 0;
      if (!mojo::internal::ReadScalar(*message, &offset, &wvc_v1)) return false;
      if (!extensions::mojom::IsKnownChannelType(wvc_v1)) return false;
      channel_type = static_cast<extensions::mojom::ChannelType>(wvc_v1);
      std::string channel_name{};
      if (!mojo::internal::ReadString(*message, &offset, &(channel_name))) return false;
      extensions::mojom::PortId port_id{};
      if (!extensions::mojom::ReadPortId(*message, &offset, &(port_id))) return false;
      uint32_t port_iid = 0;
      uint32_t port_version = 0;
      if (!mojo::internal::ReadScalar(*message, &offset, &port_iid)) return false;
      if (!mojo::internal::ReadScalar(*message, &offset, &port_version)) return false;
      mojo::PendingAssociatedRemote<extensions::mojom::MessagePort> port(router->CreateLocalEndpointHandle(port_iid), port_version);
      uint32_t port_host_iid = 0;
      if (!mojo::internal::ReadScalar(*message, &offset, &port_host_iid)) return false;
      mojo::PendingAssociatedReceiver<extensions::mojom::MessagePortHost> port_host(router->CreateLocalEndpointHandle(port_host_iid));
      impl_->OpenChannelToTab(tab_id, frame_id, document_id, channel_type, channel_name, port_id, std::move(port), std::move(port_host));
      return true;
    }

    LocalFrameHost* impl_;
    mojo::MultiplexRouter* router_;
    mojo::InterfaceId id_;
  };
};

class LocalFrameHost::Proxy_ : public LocalFrameHost, public mojo::MessageReceiver {
 public:
  explicit Proxy_(mojo::MultiplexRouter* router,
                   mojo::InterfaceId id = mojo::kPrimaryInterfaceId)
      : router_(router), id_(id) {}

  void RequestScriptInjectionPermission(const extensions::mojom::ExtensionId& extension_id, extensions::mojom::InjectionType script_type, extensions::mojom::RunLocation run_location, base::OnceCallback<void(bool)> callback) override {
    uint64_t request_id = responses_.RegisterPendingResponse(
        [callback = std::move(callback)](mojo::Message* response) mutable {
          size_t offset = 0;
          bool granted{};
          if (!mojo::internal::ReadScalar(*response, &offset, &(granted))) return false;
          std::move(callback).Run(granted);
          return true;
        });
    mojo::Message message(kRequestScriptInjectionPermissionName, mojo::Message::kFlagExpectsResponse, id_);
    message.set_request_id(request_id);
    extensions::mojom::WriteExtensionId(message, extension_id);
    mojo::internal::WriteScalar(&message, static_cast<int32_t>(script_type));
    mojo::internal::WriteScalar(&message, static_cast<int32_t>(run_location));
    (void)router_->SendMessage(&message);
  }

  void GetAppInstallState(const url::mojom::Url& url, base::OnceCallback<void(std::string)> callback) override {
    uint64_t request_id = responses_.RegisterPendingResponse(
        [callback = std::move(callback)](mojo::Message* response) mutable {
          size_t offset = 0;
          std::string state{};
          if (!mojo::internal::ReadString(*response, &offset, &(state))) return false;
          std::move(callback).Run(state);
          return true;
        });
    mojo::Message message(kGetAppInstallStateName, mojo::Message::kFlagExpectsResponse, id_);
    message.set_request_id(request_id);
    url::mojom::WriteUrl(message, url);
    (void)router_->SendMessage(&message);
  }

  void Request(const RequestParams& params, base::OnceCallback<void(bool, mojo_base::mojom::ListValue, std::string, std::optional<extensions::mojom::ExtraResponseData>)> callback) override {
    uint64_t request_id = responses_.RegisterPendingResponse(
        [callback = std::move(callback)](mojo::Message* response) mutable {
          size_t offset = 0;
          bool success{};
          if (!mojo::internal::ReadScalar(*response, &offset, &(success))) return false;
          mojo_base::mojom::ListValue response_wrapper{};
          if (!mojo_base::mojom::ReadListValue(*response, &offset, &(response_wrapper))) return false;
          std::string error{};
          if (!mojo::internal::ReadString(*response, &offset, &(error))) return false;
          std::optional<extensions::mojom::ExtraResponseData> extra_data{};
          {
            bool wvc_has0 = false;
            if (!mojo::internal::ReadScalar(*response, &offset, &wvc_has0)) return false;
            if (wvc_has0) {
              extensions::mojom::ExtraResponseData wvc_opt0{};
              if (!extensions::mojom::ReadExtraResponseData(*response, &offset, &(wvc_opt0))) return false;
              extra_data = std::move(wvc_opt0);
            } else {
              extra_data = std::nullopt;
            }
          }
          std::move(callback).Run(success, response_wrapper, error, extra_data);
          return true;
        });
    mojo::Message message(kRequestName, mojo::Message::kFlagExpectsResponse, id_);
    message.set_request_id(request_id);
    WriteRequestParams(message, params);
    (void)router_->SendMessage(&message);
  }

  void ResponseAck(const mojo_base::mojom::Uuid& request_uuid) override {
    mojo::Message message(kResponseAckName, 0, id_);
    mojo_base::mojom::WriteUuid(message, request_uuid);
    (void)router_->SendMessage(&message);
  }

  void WatchedPageChange(const v8::internal::CageVector<std::string>& css_selectors) override {
    mojo::Message message(kWatchedPageChangeName, 0, id_);
    {
      uint32_t wvc_n0 = static_cast<uint32_t>(css_selectors.size());
      message.WritePayload(&wvc_n0, sizeof(wvc_n0));
      for (const auto& wvc_e0 : css_selectors) {
        mojo::internal::WriteString(&message, wvc_e0);
      }
    }
    (void)router_->SendMessage(&message);
  }

  void DetailedConsoleMessageAdded(const mojo_base::mojom::String16& message, const mojo_base::mojom::String16& source, const v8::internal::CageVector<extensions::mojom::StackFrame>& stack_trace, blink::mojom::ConsoleMessageLevel level) override {
    mojo::Message message(kDetailedConsoleMessageAddedName, 0, id_);
    mojo_base::mojom::WriteString16(message, message);
    mojo_base::mojom::WriteString16(message, source);
    {
      uint32_t wvc_n0 = static_cast<uint32_t>(stack_trace.size());
      message.WritePayload(&wvc_n0, sizeof(wvc_n0));
      for (const auto& wvc_e0 : stack_trace) {
        extensions::mojom::WriteStackFrame(message, wvc_e0);
      }
    }
    mojo::internal::WriteScalar(&message, static_cast<int32_t>(level));
    (void)router_->SendMessage(&message);
  }

  void ContentScriptsExecuting(const v8::internal::CageMap<std::string, v8::internal::CageVector<std::string>>& extension_id_to_scripts, const url::mojom::Url& frame_url) override {
    mojo::Message message(kContentScriptsExecutingName, 0, id_);
    {
      uint32_t wvc_n0 = static_cast<uint32_t>(extension_id_to_scripts.size());
      message.WritePayload(&wvc_n0, sizeof(wvc_n0));
      for (const auto& wvc_p0 : extension_id_to_scripts) {
        mojo::internal::WriteString(&message, wvc_p0.first);
        {
          uint32_t wvc_n1 = static_cast<uint32_t>(wvc_p0.second.size());
          message.WritePayload(&wvc_n1, sizeof(wvc_n1));
          for (const auto& wvc_e1 : wvc_p0.second) {
            mojo::internal::WriteString(&message, wvc_e1);
          }
        }
      }
    }
    url::mojom::WriteUrl(message, frame_url);
    (void)router_->SendMessage(&message);
  }

  void IncrementLazyKeepaliveCount() override {
    mojo::Message message(kIncrementLazyKeepaliveCountName, 0, id_);
    (void)router_->SendMessage(&message);
  }

  void DecrementLazyKeepaliveCount() override {
    mojo::Message message(kDecrementLazyKeepaliveCountName, 0, id_);
    (void)router_->SendMessage(&message);
  }

  void AppWindowReady() override {
    mojo::Message message(kAppWindowReadyName, 0, id_);
    (void)router_->SendMessage(&message);
  }

  void OpenChannelToExtension(const extensions::mojom::ExternalConnectionInfo& info, extensions::mojom::ChannelType channel_type, const std::string& channel_name, const extensions::mojom::PortId& port_id, mojo::PendingAssociatedRemote<extensions::mojom::MessagePort> port, mojo::PendingAssociatedReceiver<extensions::mojom::MessagePortHost> port_host) override {
    uint32_t port_version = port.version();
    mojo::ScopedInterfaceEndpointHandle port_handle = port.PassHandle();
    uint32_t port_iid = port_handle.ReleaseWithoutClosing();
    mojo::ScopedInterfaceEndpointHandle port_host_handle = port_host.PassHandle();
    uint32_t port_host_iid = port_host_handle.ReleaseWithoutClosing();
    mojo::Message message(kOpenChannelToExtensionName, 0, id_);
    extensions::mojom::WriteExternalConnectionInfo(message, info);
    mojo::internal::WriteScalar(&message, static_cast<int32_t>(channel_type));
    mojo::internal::WriteString(&message, channel_name);
    extensions::mojom::WritePortId(message, port_id);
    message.WritePayload(&port_iid, sizeof(port_iid));
    message.WritePayload(&port_version, sizeof(port_version));
    message.WritePayload(&port_host_iid, sizeof(port_host_iid));
    (void)router_->SendMessage(&message);
  }

  void OpenChannelToNativeApp(const std::string& native_app_name, const v8::internal::CageVector<std::array<uint8_t, 32>>& android_certificates, const extensions::mojom::PortId& port_id, mojo::PendingAssociatedRemote<extensions::mojom::MessagePort> port, mojo::PendingAssociatedReceiver<extensions::mojom::MessagePortHost> port_host) override {
    uint32_t port_version = port.version();
    mojo::ScopedInterfaceEndpointHandle port_handle = port.PassHandle();
    uint32_t port_iid = port_handle.ReleaseWithoutClosing();
    mojo::ScopedInterfaceEndpointHandle port_host_handle = port_host.PassHandle();
    uint32_t port_host_iid = port_host_handle.ReleaseWithoutClosing();
    mojo::Message message(kOpenChannelToNativeAppName, 0, id_);
    mojo::internal::WriteString(&message, native_app_name);
    {
      uint32_t wvc_n0 = static_cast<uint32_t>(android_certificates.size());
      message.WritePayload(&wvc_n0, sizeof(wvc_n0));
      for (const auto& wvc_e0 : android_certificates) {
        {
          for (const auto& wvc_e1 : wvc_e0) {
            mojo::internal::WriteScalar(&message, wvc_e1);
          }
        }
      }
    }
    extensions::mojom::WritePortId(message, port_id);
    message.WritePayload(&port_iid, sizeof(port_iid));
    message.WritePayload(&port_version, sizeof(port_version));
    message.WritePayload(&port_host_iid, sizeof(port_host_iid));
    (void)router_->SendMessage(&message);
  }

  void OpenChannelToTab(int32_t tab_id, int32_t frame_id, const std::optional<std::string>& document_id, extensions::mojom::ChannelType channel_type, const std::string& channel_name, const extensions::mojom::PortId& port_id, mojo::PendingAssociatedRemote<extensions::mojom::MessagePort> port, mojo::PendingAssociatedReceiver<extensions::mojom::MessagePortHost> port_host) override {
    uint32_t port_version = port.version();
    mojo::ScopedInterfaceEndpointHandle port_handle = port.PassHandle();
    uint32_t port_iid = port_handle.ReleaseWithoutClosing();
    mojo::ScopedInterfaceEndpointHandle port_host_handle = port_host.PassHandle();
    uint32_t port_host_iid = port_host_handle.ReleaseWithoutClosing();
    mojo::Message message(kOpenChannelToTabName, 0, id_);
    mojo::internal::WriteScalar(&message, tab_id);
    mojo::internal::WriteScalar(&message, frame_id);
    {
      bool wvc_has0 = document_id.has_value();
      mojo::internal::WriteScalar(&message, wvc_has0);
      if (wvc_has0) {
        mojo::internal::WriteString(&message, (*document_id));
      }
    }
    mojo::internal::WriteScalar(&message, static_cast<int32_t>(channel_type));
    mojo::internal::WriteString(&message, channel_name);
    extensions::mojom::WritePortId(message, port_id);
    message.WritePayload(&port_iid, sizeof(port_iid));
    message.WritePayload(&port_version, sizeof(port_version));
    message.WritePayload(&port_host_iid, sizeof(port_host_iid));
    (void)router_->SendMessage(&message);
  }

  void QueryVersion(base::OnceCallback<void(uint32_t)> callback) {
    uint64_t request_id = responses_.RegisterPendingResponse(
        [callback = std::move(callback)](mojo::Message* response) mutable {
          size_t offset = 0;
          uint32_t tag = 0;
          uint32_t version = 0;
          if (!mojo::internal::ReadScalar(*response, &offset, &tag) ||
              tag != mojo::internal::kRunQueryVersionResult ||
              !mojo::internal::ReadScalar(*response, &offset, &version)) {
            return false;
          }
          std::move(callback).Run(version);
          return true;
        });
    mojo::Message message(mojo::internal::kRunMessageId,
                          mojo::Message::kFlagExpectsResponse, id_);
    message.set_request_id(request_id);
    mojo::internal::WriteScalar(&message, mojo::internal::kRunQueryVersion);
    (void)router_->SendMessage(&message);
  }

  void RequireVersion(uint32_t version) {
    mojo::Message message(mojo::internal::kRunOrClosePipeMessageId, 0, id_);
    mojo::internal::WriteScalar(&message, mojo::internal::kRunRequireVersion);
    mojo::internal::WriteScalar(&message, version);
    (void)router_->SendMessage(&message);
  }

  [[nodiscard]] bool Accept(mojo::Message* message) override {
    if (!message->has_flag(mojo::Message::kFlagIsResponse)) {
      return false;
    }
    return responses_.DispatchResponse(message);
  }

 private:
  mojo::MultiplexRouter* router_;
  mojo::InterfaceId id_;
  mojo::internal::ResponseDispatcher responses_;
};

}  // namespace mojom
}  // namespace extensions

#endif  // FRAME_EXTENSIONS_H_
