// Generated by WASMVoodooCompile (voodoomc) from 'C:\Users\grego\Bruja\third_party\chromium-src\android_webview\common\mojom\frame.mojom'. Do not edit by hand -- edit the .voodoom source and regenerate.
#ifndef FRAME_ANDROID_WEBVIEW_H_
#define FRAME_ANDROID_WEBVIEW_H_

#include "mojo/public/cpp/bindings/lib/interface_control_messages.h"
#include "mojo/public/cpp/bindings/lib/multiplex_router.h"
#include "mojo/public/cpp/bindings/lib/response_dispatcher.h"
#include "mojo/public/cpp/bindings/lib/wire_primitives.h"
#include "mojo/public/cpp/bindings/message.h"
#include "src/sandbox/cage-allocator.h"
#include "mojo/public/cpp/bindings/pending_associated_receiver.h"
#include "mojo/public/cpp/bindings/pending_associated_remote.h"
#include "mojo/public/cpp/bindings/pending_receiver.h"
#include "mojo/public/cpp/bindings/pending_remote.h"
#include "base/callback.h"
#include "base/expected.h"
#include "mojo/public/cpp/bindings/lib/type_intern.h"
#include "mojo/public/cpp/system/handle.h"
#include "mojo/public/cpp/system/platform_handle.h"
#include "mojo/public/cpp/system/message_pipe.h"
#include "mojo/public/cpp/system/data_pipe.h"
#include "mojo/public/cpp/system/buffer.h"

#include <array>
#include <cstdint>
#include <cstring>
#include <limits>
#include <functional>
#include <optional>
#include <string>
#include <unordered_map>
#include <utility>
#include <vector>

#include "string16_gen.h"
#include "time_gen.h"
#include "geometry_gen.h"
#include "url_gen.h"

#ifndef MOJO_NATIVE_TRAITS_DEFINED
#define MOJO_NATIVE_TRAITS_DEFINED
namespace mojo {
template <typename T>
struct NativeTraits {
  static void Write(Message&, const T&) = delete;
  static bool Read(const Message&, size_t*, T*) = delete;
};
}  // namespace mojo
#endif

namespace android_webview {
namespace mojom {

class LocalMainFrame;
class FrameHost;

struct HitTestData;

enum class HitTestDataType : int32_t {
  kUnknown = 0,
  kPhone = 2,
  kGeo = 3,
  kEmail = 4,
  kImage = 5,
  kSrcLink = 7,
  kSrcImageLink = 8,
  kEditText = 9,
};

inline bool IsKnownHitTestDataType(int32_t wvc_value) {
  switch (wvc_value) {
    case 0:
    case 2:
    case 3:
    case 4:
    case 5:
    case 7:
    case 8:
    case 9:
      return true;
    default:
      return false;
  }
}

inline bool IsKnownHitTestDataTypeAsOf(int32_t wvc_value, uint32_t wvc_version) {
  (void)wvc_version;
  switch (wvc_value) {
    case 0:
      return true;
    case 2:
      return true;
    case 3:
      return true;
    case 4:
      return true;
    case 5:
      return true;
    case 7:
      return true;
    case 8:
      return true;
    case 9:
      return true;
    default:
      return false;
  }
}

struct HitTestData {
  HitTestDataType type{};
  std::string extra_data_for_type{};
  mojo_base::mojom::String16 href{};
  mojo_base::mojom::String16 anchor_text{};
  url::mojom::Url img_src{};
  // Object Type Identifier: intern_key is the shape string (Go++ go/types intern);
  // type_key() is the C++ token (Go++ type_key_of<T>()); CHPT names objects
  // with the interned tag (WASMv8Bindings + WASMSafeSpace). FromHandle fails
  // unless the tag matches.
  static constexpr const char* intern_key() { return "struct:android_webview.mojom.HitTestData"; }
  static const void* type_key() { static char k; return &k; }
  static v8::CppHeapPointerTag chpt_tag() {
    return mojo::internal::TypeTag(type_key());
  }
  static v8::CppHeapPointerHandle NameOnHeap(HitTestData* p) {
    return mojo::internal::NameObject(p, type_key());
  }
  static HitTestData* FromHandle(v8::CppHeapPointerHandle h) {
    return static_cast<HitTestData*>(mojo::internal::GetObject(h, type_key()));
  }
};

void WriteHitTestData(mojo::Message& message, const HitTestData& value);
bool ReadHitTestData(const mojo::Message& message, size_t* offset, HitTestData* out);

inline void WriteHitTestData(mojo::Message& message, const HitTestData& value) {
  size_t wvc_header_offset = message.payload_num_bytes();
  mojo::internal::WriteStructHeader(&message, 0, 0);
  mojo::internal::WriteScalar(&message, static_cast<int32_t>(value.type));
  mojo::internal::WriteString(&message, value.extra_data_for_type);
  mojo_base::mojom::WriteString16(message, value.href);
  mojo_base::mojom::WriteString16(message, value.anchor_text);
  url::mojom::WriteUrl(message, value.img_src);
  mojo::internal::PatchStructHeader(
      message.mutable_payload() + wvc_header_offset,
      static_cast<uint32_t>(message.payload_num_bytes() - wvc_header_offset),
      0u);
}

inline bool ReadHitTestData(const mojo::Message& message, size_t* offset, HitTestData* out) {
  uint32_t wvc_num_bytes = 0;
  uint32_t wvc_version = 0;
  if (!mojo::internal::ReadStructHeader(message, offset, &wvc_num_bytes, &wvc_version)) {
    return false;
  }
  if (wvc_num_bytes < 8u) return false;
  size_t wvc_struct_end =
      *offset - 8u + wvc_num_bytes;
  if (wvc_struct_end > message.payload_num_bytes()) return false;
  int32_t wvc_v0 = 0;
  if (!mojo::internal::ReadScalar(message, offset, &wvc_v0)) return false;
  if (!IsKnownHitTestDataTypeAsOf(wvc_v0, wvc_version)) return false;
  out->type = static_cast<HitTestDataType>(wvc_v0);
  if (!mojo::internal::ReadString(message, offset, &(out->extra_data_for_type))) return false;
  if (!mojo_base::mojom::ReadString16(message, offset, &(out->href))) return false;
  if (!mojo_base::mojom::ReadString16(message, offset, &(out->anchor_text))) return false;
  if (!url::mojom::ReadUrl(message, offset, &(out->img_src))) return false;
  *offset = wvc_struct_end;
  return true;
}

class LocalMainFrame {
 public:
  virtual ~LocalMainFrame() = default;
  virtual void SetInitialPageScale(double page_scale_factor) = 0;
  virtual void SetTextZoomFactor(float zoom_factor) = 0;
  virtual void DocumentHasImage(base::OnceCallback<void(bool)> callback) = 0;
  virtual void ResetScrollAndScaleState() = 0;
  virtual void SmoothScroll(int32_t target_x, int32_t target_y, const mojo_base::mojom::TimeDelta& duration) = 0;

  static constexpr uint32_t kSetInitialPageScaleName = 0;
  static constexpr uint32_t kSetTextZoomFactorName = 1;
  static constexpr uint32_t kDocumentHasImageName = 2;
  static constexpr uint32_t kResetScrollAndScaleStateName = 3;
  static constexpr uint32_t kSmoothScrollName = 4;
  static constexpr uint32_t kVersion = 0u;

  // Object Type Identifier: intern_key is the shape string (Go++ go/types intern);
  // type_key() is the C++ token (Go++ type_key_of<T>()); CHPT names objects
  // with the interned tag (WASMv8Bindings + WASMSafeSpace). FromHandle fails
  // unless the tag matches.
  static constexpr const char* intern_key() { return "interface:android_webview.mojom.LocalMainFrame"; }
  static const void* type_key() { static char k; return &k; }
  static v8::CppHeapPointerTag chpt_tag() {
    return mojo::internal::TypeTag(type_key());
  }
  static v8::CppHeapPointerHandle NameOnHeap(LocalMainFrame* p) {
    return mojo::internal::NameObject(p, type_key());
  }
  static LocalMainFrame* FromHandle(v8::CppHeapPointerHandle h) {
    return static_cast<LocalMainFrame*>(mojo::internal::GetObject(h, type_key()));
  }
  class Proxy_;  // defined below, once LocalMainFrame is a complete type

  class Stub_ : public mojo::MessageReceiver {
   public:
    Stub_(LocalMainFrame* impl,
          mojo::MultiplexRouter* router,
          mojo::InterfaceId id = mojo::kPrimaryInterfaceId)
        : impl_(impl), router_(router), id_(id) {}

    [[nodiscard]] bool Accept(mojo::Message* message) override {
      if (message->name() == mojo::internal::kRunMessageId) {
        return mojo::internal::HandleQueryVersionMessage(
            message, router_, id_, kVersion);
      }
      if (message->name() == mojo::internal::kRunOrClosePipeMessageId) {
        return mojo::internal::HandleRequireVersionMessage(
            *message, kVersion);
      }
      if (message->name() == kSetInitialPageScaleName) return AcceptSetInitialPageScale(message);
      if (message->name() == kSetTextZoomFactorName) return AcceptSetTextZoomFactor(message);
      if (message->name() == kDocumentHasImageName) return AcceptDocumentHasImage(message);
      if (message->name() == kResetScrollAndScaleStateName) return AcceptResetScrollAndScaleState(message);
      if (message->name() == kSmoothScrollName) return AcceptSmoothScroll(message);
      return false;
    }

   private:
    bool AcceptSetInitialPageScale(mojo::Message* message) {
      size_t offset = 0;
      double page_scale_factor{};
      if (!mojo::internal::ReadScalar(*message, &offset, &(page_scale_factor))) return false;
      impl_->SetInitialPageScale(page_scale_factor);
      return true;
    }

    bool AcceptSetTextZoomFactor(mojo::Message* message) {
      size_t offset = 0;
      float zoom_factor{};
      if (!mojo::internal::ReadScalar(*message, &offset, &(zoom_factor))) return false;
      impl_->SetTextZoomFactor(zoom_factor);
      return true;
    }

    bool AcceptDocumentHasImage(mojo::Message* message) {
      size_t offset = 0;
      (void)offset;
      const uint64_t request_id = message->request_id();
      mojo::MultiplexRouter* router = router_;
      const mojo::InterfaceId id = id_;
      impl_->DocumentHasImage([router, id, request_id](bool has_images) {
        mojo::Message response(LocalMainFrame::kDocumentHasImageName, mojo::Message::kFlagIsResponse, id);
        response.set_request_id(request_id);
        mojo::internal::WriteScalar(&response, has_images);
        (void)router->SendMessage(&response);
      });
      return true;
    }

    bool AcceptResetScrollAndScaleState(mojo::Message* message) {
      size_t offset = 0;
      (void)message;
      (void)offset;
      impl_->ResetScrollAndScaleState();
      return true;
    }

    bool AcceptSmoothScroll(mojo::Message* message) {
      size_t offset = 0;
      int32_t target_x{};
      if (!mojo::internal::ReadScalar(*message, &offset, &(target_x))) return false;
      int32_t target_y{};
      if (!mojo::internal::ReadScalar(*message, &offset, &(target_y))) return false;
      mojo_base::mojom::TimeDelta duration{};
      if (!mojo_base::mojom::ReadTimeDelta(*message, &offset, &(duration))) return false;
      impl_->SmoothScroll(target_x, target_y, duration);
      return true;
    }

    LocalMainFrame* impl_;
    mojo::MultiplexRouter* router_;
    mojo::InterfaceId id_;
  };
};

class LocalMainFrame::Proxy_ : public LocalMainFrame, public mojo::MessageReceiver {
 public:
  explicit Proxy_(mojo::MultiplexRouter* router,
                   mojo::InterfaceId id = mojo::kPrimaryInterfaceId)
      : router_(router), id_(id) {}

  void SetInitialPageScale(double page_scale_factor) override {
    mojo::Message message(kSetInitialPageScaleName, 0, id_);
    mojo::internal::WriteScalar(&message, page_scale_factor);
    (void)router_->SendMessage(&message);
  }

  void SetTextZoomFactor(float zoom_factor) override {
    mojo::Message message(kSetTextZoomFactorName, 0, id_);
    mojo::internal::WriteScalar(&message, zoom_factor);
    (void)router_->SendMessage(&message);
  }

  void DocumentHasImage(base::OnceCallback<void(bool)> callback) override {
    uint64_t request_id = responses_.RegisterPendingResponse(
        [callback = std::move(callback)](mojo::Message* response) mutable {
          size_t offset = 0;
          bool has_images{};
          if (!mojo::internal::ReadScalar(*response, &offset, &(has_images))) return false;
          std::move(callback).Run(has_images);
          return true;
        });
    mojo::Message message(kDocumentHasImageName, mojo::Message::kFlagExpectsResponse, id_);
    message.set_request_id(request_id);
    (void)router_->SendMessage(&message);
  }

  void ResetScrollAndScaleState() override {
    mojo::Message message(kResetScrollAndScaleStateName, 0, id_);
    (void)router_->SendMessage(&message);
  }

  void SmoothScroll(int32_t target_x, int32_t target_y, const mojo_base::mojom::TimeDelta& duration) override {
    mojo::Message message(kSmoothScrollName, 0, id_);
    mojo::internal::WriteScalar(&message, target_x);
    mojo::internal::WriteScalar(&message, target_y);
    mojo_base::mojom::WriteTimeDelta(message, duration);
    (void)router_->SendMessage(&message);
  }

  void QueryVersion(base::OnceCallback<void(uint32_t)> callback) {
    uint64_t request_id = responses_.RegisterPendingResponse(
        [callback = std::move(callback)](mojo::Message* response) mutable {
          size_t offset = 0;
          uint32_t tag = 0;
          uint32_t version = 0;
          if (!mojo::internal::ReadScalar(*response, &offset, &tag) ||
              tag != mojo::internal::kRunQueryVersionResult ||
              !mojo::internal::ReadScalar(*response, &offset, &version)) {
            return false;
          }
          std::move(callback).Run(version);
          return true;
        });
    mojo::Message message(mojo::internal::kRunMessageId,
                          mojo::Message::kFlagExpectsResponse, id_);
    message.set_request_id(request_id);
    mojo::internal::WriteScalar(&message, mojo::internal::kRunQueryVersion);
    (void)router_->SendMessage(&message);
  }

  void RequireVersion(uint32_t version) {
    mojo::Message message(mojo::internal::kRunOrClosePipeMessageId, 0, id_);
    mojo::internal::WriteScalar(&message, mojo::internal::kRunRequireVersion);
    mojo::internal::WriteScalar(&message, version);
    (void)router_->SendMessage(&message);
  }

  [[nodiscard]] bool Accept(mojo::Message* message) override {
    if (!message->has_flag(mojo::Message::kFlagIsResponse)) {
      return false;
    }
    return responses_.DispatchResponse(message);
  }

 private:
  mojo::MultiplexRouter* router_;
  mojo::InterfaceId id_;
  mojo::internal::ResponseDispatcher responses_;
};

class FrameHost {
 public:
  virtual ~FrameHost() = default;
  virtual void UpdateHitTestData(const HitTestData& data) = 0;
  virtual void ContentsSizeChanged(const gfx::mojom::Size& contents_size) = 0;
  virtual void ShouldOverrideUrlLoading(const mojo_base::mojom::String16& url, bool has_user_gesture, base::OnceCallback<void(bool)> callback) = 0;

  static constexpr uint32_t kUpdateHitTestDataName = 0;
  static constexpr uint32_t kContentsSizeChangedName = 1;
  static constexpr uint32_t kShouldOverrideUrlLoadingName = 2;
  static constexpr uint32_t kVersion = 0u;

  // Object Type Identifier: intern_key is the shape string (Go++ go/types intern);
  // type_key() is the C++ token (Go++ type_key_of<T>()); CHPT names objects
  // with the interned tag (WASMv8Bindings + WASMSafeSpace). FromHandle fails
  // unless the tag matches.
  static constexpr const char* intern_key() { return "interface:android_webview.mojom.FrameHost"; }
  static const void* type_key() { static char k; return &k; }
  static v8::CppHeapPointerTag chpt_tag() {
    return mojo::internal::TypeTag(type_key());
  }
  static v8::CppHeapPointerHandle NameOnHeap(FrameHost* p) {
    return mojo::internal::NameObject(p, type_key());
  }
  static FrameHost* FromHandle(v8::CppHeapPointerHandle h) {
    return static_cast<FrameHost*>(mojo::internal::GetObject(h, type_key()));
  }
  class Proxy_;  // defined below, once FrameHost is a complete type

  class Stub_ : public mojo::MessageReceiver {
   public:
    Stub_(FrameHost* impl,
          mojo::MultiplexRouter* router,
          mojo::InterfaceId id = mojo::kPrimaryInterfaceId)
        : impl_(impl), router_(router), id_(id) {}

    [[nodiscard]] bool Accept(mojo::Message* message) override {
      if (message->name() == mojo::internal::kRunMessageId) {
        return mojo::internal::HandleQueryVersionMessage(
            message, router_, id_, kVersion);
      }
      if (message->name() == mojo::internal::kRunOrClosePipeMessageId) {
        return mojo::internal::HandleRequireVersionMessage(
            *message, kVersion);
      }
      if (message->name() == kUpdateHitTestDataName) return AcceptUpdateHitTestData(message);
      if (message->name() == kContentsSizeChangedName) return AcceptContentsSizeChanged(message);
      if (message->name() == kShouldOverrideUrlLoadingName) return AcceptShouldOverrideUrlLoading(message);
      return false;
    }

   private:
    bool AcceptUpdateHitTestData(mojo::Message* message) {
      size_t offset = 0;
      HitTestData data{};
      if (!ReadHitTestData(*message, &offset, &(data))) return false;
      impl_->UpdateHitTestData(data);
      return true;
    }

    bool AcceptContentsSizeChanged(mojo::Message* message) {
      size_t offset = 0;
      gfx::mojom::Size contents_size{};
      if (!gfx::mojom::ReadSize(*message, &offset, &(contents_size))) return false;
      impl_->ContentsSizeChanged(contents_size);
      return true;
    }

    bool AcceptShouldOverrideUrlLoading(mojo::Message* message) {
      size_t offset = 0;
      mojo_base::mojom::String16 url{};
      if (!mojo_base::mojom::ReadString16(*message, &offset, &(url))) return false;
      bool has_user_gesture{};
      if (!mojo::internal::ReadScalar(*message, &offset, &(has_user_gesture))) return false;
      const uint64_t request_id = message->request_id();
      mojo::MultiplexRouter* router = router_;
      const mojo::InterfaceId id = id_;
      impl_->ShouldOverrideUrlLoading(url, has_user_gesture, [router, id, request_id](bool result) {
        mojo::Message response(FrameHost::kShouldOverrideUrlLoadingName, mojo::Message::kFlagIsResponse, id);
        response.set_request_id(request_id);
        mojo::internal::WriteScalar(&response, result);
        (void)router->SendMessage(&response);
      });
      return true;
    }

    FrameHost* impl_;
    mojo::MultiplexRouter* router_;
    mojo::InterfaceId id_;
  };
};

class FrameHost::Proxy_ : public FrameHost, public mojo::MessageReceiver {
 public:
  explicit Proxy_(mojo::MultiplexRouter* router,
                   mojo::InterfaceId id = mojo::kPrimaryInterfaceId)
      : router_(router), id_(id) {}

  void UpdateHitTestData(const HitTestData& data) override {
    mojo::Message message(kUpdateHitTestDataName, 0, id_);
    WriteHitTestData(message, data);
    (void)router_->SendMessage(&message);
  }

  void ContentsSizeChanged(const gfx::mojom::Size& contents_size) override {
    mojo::Message message(kContentsSizeChangedName, 0, id_);
    gfx::mojom::WriteSize(message, contents_size);
    (void)router_->SendMessage(&message);
  }

  void ShouldOverrideUrlLoading(const mojo_base::mojom::String16& url, bool has_user_gesture, base::OnceCallback<void(bool)> callback) override {
    uint64_t request_id = responses_.RegisterPendingResponse(
        [callback = std::move(callback)](mojo::Message* response) mutable {
          size_t offset = 0;
          bool result{};
          if (!mojo::internal::ReadScalar(*response, &offset, &(result))) return false;
          std::move(callback).Run(result);
          return true;
        });
    mojo::Message message(kShouldOverrideUrlLoadingName, mojo::Message::kFlagExpectsResponse, id_);
    message.set_request_id(request_id);
    mojo_base::mojom::WriteString16(message, url);
    mojo::internal::WriteScalar(&message, has_user_gesture);
    (void)router_->SendMessage(&message);
  }

  // [Sync] blocking overload -- see WASMCadidumBindings'
  // Connector::SyncWaitFor for what "blocking" means here.
  [[nodiscard]] bool ShouldOverrideUrlLoading(const mojo_base::mojom::String16& url, bool has_user_gesture, bool* result) {
    bool wvc_sync_done = false;
    bool wvc_sync_result{};
    uint64_t request_id = responses_.RegisterPendingResponse(
        [&](mojo::Message* response) {
          size_t offset = 0;
          bool result{};
          if (!mojo::internal::ReadScalar(*response, &offset, &(result))) return false;
          wvc_sync_result = std::move(result);
          wvc_sync_done = true;
          return true;
        });
    mojo::Message message(FrameHost::kShouldOverrideUrlLoadingName, mojo::Message::kFlagExpectsResponse, id_);
    message.set_request_id(request_id);
    mojo_base::mojom::WriteString16(message, url);
    mojo::internal::WriteScalar(&message, has_user_gesture);
    if (!router_->SendMessage(&message)) return false;
    if (!router_->connector().SyncWaitFor(
            [&] { return wvc_sync_done; })) {
      return false;
    }
    *result = std::move(wvc_sync_result);
    return true;
  }

  void QueryVersion(base::OnceCallback<void(uint32_t)> callback) {
    uint64_t request_id = responses_.RegisterPendingResponse(
        [callback = std::move(callback)](mojo::Message* response) mutable {
          size_t offset = 0;
          uint32_t tag = 0;
          uint32_t version = 0;
          if (!mojo::internal::ReadScalar(*response, &offset, &tag) ||
              tag != mojo::internal::kRunQueryVersionResult ||
              !mojo::internal::ReadScalar(*response, &offset, &version)) {
            return false;
          }
          std::move(callback).Run(version);
          return true;
        });
    mojo::Message message(mojo::internal::kRunMessageId,
                          mojo::Message::kFlagExpectsResponse, id_);
    message.set_request_id(request_id);
    mojo::internal::WriteScalar(&message, mojo::internal::kRunQueryVersion);
    (void)router_->SendMessage(&message);
  }

  void RequireVersion(uint32_t version) {
    mojo::Message message(mojo::internal::kRunOrClosePipeMessageId, 0, id_);
    mojo::internal::WriteScalar(&message, mojo::internal::kRunRequireVersion);
    mojo::internal::WriteScalar(&message, version);
    (void)router_->SendMessage(&message);
  }

  [[nodiscard]] bool Accept(mojo::Message* message) override {
    if (!message->has_flag(mojo::Message::kFlagIsResponse)) {
      return false;
    }
    return responses_.DispatchResponse(message);
  }

 private:
  mojo::MultiplexRouter* router_;
  mojo::InterfaceId id_;
  mojo::internal::ResponseDispatcher responses_;
};

}  // namespace mojom
}  // namespace android_webview

#endif  // FRAME_ANDROID_WEBVIEW_H_
